# docker-compose.yml
version: '3.9'
services:
  app:
    build: .
    container_name: my_automation_app
    volumes:
      - ./data:/data
      - ./app:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    network_mode: "host"


